services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/snippets
      - AI_PROVIDER=gemini
      - AI_PROVIDER_KEY=fake-key
      - JWT_SECRET=your-key
      - FRONTEND_URL=http://localhost:3030
    depends_on:
      - mongo
    networks:
      - default
    command: sh -c "npm run test && npm run build && node dist/server.js"

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - default
    volumes:
      - mongo-data:/data/db

networks:
  default:
    external: true
    name: shared-network

volumes:
  mongo-data:
    driver: local
